### ISSUE TITLE
render관련 고도화 기능

### ISSUE THREAD

**Issue by intelliguy** [openinfradev/decapod-site-yaml#1]
## 개요
현재 decapod는 다음의 과정을 거쳐서 실제 배포함

1. site에 맞는 value 작성 (decapod-site-yaml)
2. 랜더링 과정 (render.sh 또는 docker 명령, github-action 등을 토대로 최종 manifest 생성)
3. 이를 다시 git에 올림
4. argo-workflow에  해당 repo.를 지정 후 pull (prepare-job)
5. argo-workflow에서 app별 적용

이 과정에서 2,3,4는 사용자에게 별다른 효용을 주지 않는 것으로 이를 동시에 수행하는 workflow를 작성하여 제공한다면 편의가 증대될 것임

## 개선방향 제안

1. 사용자는 decapod-site-yaml을 folk하여 site 특화 값을 지정
2. argo-workflow에서 해당 repo.를 지정 후 prepare-job 수행
3. argo-workflow에서 app별 적용

**Comment by robertchoi80** [comment]
제안 자체는 reasonable한 방향이라 실제로 한번 시도해보고 판단해보는게 좋을 것 같습니다.  다만 개선방향대로 할 경우, site-yaml PR시 github action 에서 workflow를 호출해서 (1) "manifest가 잘 merge되고", + (2) "실제 배포 진행" 하는 테스트 후에 결과를 다시 github 쪽에 notify해주는 flow에 대해 고민이 필요하겠네요.  1)번만 할지 1) + 2) 까지 수행할지는 선택의 문제이지만 가능하면 다 해보는게 좀더 확실하긴 하겠죠

**Comment by bluejayA** [comment]
어제 잠깐 이야기했지만, decapod-site-yaml에 PR을 올리는 과정에서 merge전 gating이 필요합니다. 
따라서, 최소한으로는 output이 에러없이 잘 render되는지를 봐야 할 듯 하고, 그외에도 "논의에 따라" 실제 배포까지 되는지를 체크하는 gating job을 둘 수도 있습니다. 

따라서, 제안한 것 처럼 개선이 된다고 하더라도, decapod-site-yaml에 PR을 올렸을 때 돌아야 하는 gating job들은 유지가 되어야 할 것으로 생각됩니다. (혹은 필요시 쉽게 추가가 가능해야 하거나). 이 부분은 문제가 없을지요? 

(앗 위에 @robertchoi80 님이 비슷한 내용을 이미 올리셨네요)

**Comment by bluejayA** [comment]
> 사용자가 output manifest를 볼 니즈가 없다면 이대로 진행하면 될 것 같습니다.

"니즈" 부분에 대해서는 실제 구축을 많이 해보신 @zugwan 님, @iksungjeon 님, 혹은 @prudentcircle 님 의견도 들었으면 합니다.

**Comment by zugwan** [comment]
output manifest를 생성하고 확인해 볼 수 있는 방법만 제공된다면 중간 과정을 제거하고 자동화하는 현 개선안이 나을 듯 합니다.

**Comment by estherk0** [comment]
위의 의견들을 토대로 다음과 같이 정리하였습니다.

결론
---
* argo workflow를 통한 [variant](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#variant) 렌더링 자동화.
  : `prepare-manifest` 에서 [variant](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#variant)를 만들고, github repo에서는 output manifest를 저장하지 않는다.
* local에서 렌더링을 해볼 수 있는 방법 제공

TODO
---
* `prepare-manifest` workflow 수정
* decapod-site-yaml output/ 삭제 작업 
* local 렌더링/테스트 방법과 문서 제공

**Comment by intelliguy** [comment]
> 위의 의견들을 토대로 다음과 같이 정리하였습니다.
> 
> ## 결론
> * argo workflow를 통한 [variant](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#variant) 렌더링 자동화.
>   : `prepare-manifest` 에서 [variant](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#variant)를 만들고, github repo에서는 output manifest를 저장하지 않는다.
> * local에서 렌더링을 해볼 수 있는 방법 제공
> 
> ## TODO
> * `prepare-manifest` workflow 수정
> * decapod-site-yaml output/ 삭제 작업
> * local 렌더링/테스트 방법과 문서 제공

LGTM

**Comment by estherk0** [comment]
TODO 리스트를 이슈로 등록했습니다.
