### ISSUE TITLE
Support local render tool and guide

### ISSUE THREAD

**Issue by estherk0** [openinfradev/decapod-site-yaml#4]
Issue from [#1](https://github.com/openinfradev/decapod-site-yaml/issues/1)

**Comment by robertchoi80** [comment]
한가지 궁금한 점이 있는데, output manifest 를 삭제된다고 해도, PR 제출시 기본적인 lint test 는 수행하는 거죠?  하게 된다면 이 부분도 argo workflow로 하게 될까요 아니면 다른 간단한 방법으로 하게 되나요?

**Comment by estherk0** [comment]
@robertchoi80 네 lint test는 github action으로 할 예정입니다.
